const ROLE = {
    ADMIN: "ADMIN",
    MERCHANT: "MERCHANT",
};

const DEVISE = {
    EURO: "EURO",
    DOLLAR: "DOLLAR",
    YEN: "YEN",
    HRYVNIA: "HRYVNIA",
};

const MERCHANT_STATUS = {
    CONFIRMED: "CONFIRMED",
    PENDING: "PENDING",
    BANNED: "BANNED",
    DISABLED: "DISABLED",
};

const OPERATIONS_STATE = {
    CREATED: "CREATED",
    PROCESSING: "PROCESSING",
    DONE: "DONE",
};

const OPERATIONS_TYPE = {
    CAPTURE: "CAPTURE",
    REFUNDED: "REFUNDED",
};

export { ROLE, DEVISE, MERCHANT_STATUS, OPERATIONS_TYPE, OPERATIONS_STATE };
