version: "3.1"

services:
    mongo:
        image: mongo
        ports:
            - 27018:27018
        command: mongod --port 27018
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: dbpayment
        volumes:
            - mongo-data:/data/db

    mongo-express:
        image: mongo-express
        depends_on:
            - mongo
        ports:
            - 127.0.0.1:8088:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_MONGODB_PORT: 27018

    server-psp:
        image: node:alpine
        volumes:
            - "./server-psp:/home/node/app:rw,consistent"
        working_dir: "/home/node/app"
        environment:
            PSP_SECRET: "MonSuperPspSecretLol"

        command: "npm run start"
        ports:
            - 127.0.0.1:3005:3005

    server:
        image: node:alpine
        volumes:
            - "./server:/home/node/app:rw,consistent"
        working_dir: "/home/node/app"
        environment:
            MONGODB_USER: "root"
            MONGODB_PASS: "password"
            MONGODB_DBNAME: "dbpayment"
            DATABASE_URL: "postgres://user:password@postgres:5432/dbpayment"
            JWT_SECRET: "MyBestSecret"
            MAILER_USER: "payplus.info2020@gmail.com"
            MAILER_PASS: "paypluas2020"
            BASE_URL: "http://localhost:3050"
            PSP_SECRET: "MonSuperPspSecretLol"
        depends_on:
            - postgres
            - pgadmin
            - mongo-express
            - server-psp
            - server-merchant
        command: "npm run dev"
        ports:
            - 127.0.0.1:3050:3050

    server-merchant:
        image: node:alpine
        volumes:
            - "./server-marchand:/home/node/app:rw,consistent"
        working_dir: "/home/node/app"
        environment:
            MONGODB_USER: "root"
            MONGODB_PASS: "password"
            MONGODB_DBNAME: "dbmerchant"
            BASE_URL: "http://localhost:3050"
        depends_on:
            - mongo-express
        command: "npm run start"
        ports:
            - 127.0.0.1:3001:3001

    client:
        build: "./docker"
        volumes:
            - "./client:/home/node/app"
        working_dir: "/home/node/app"
        command: "yarn start"
        tty: true
        stdin_open: true
        ports:
            - 127.0.0.1:3000:3000
        environment:
            REACT_APP_BACK_OFFICE_URL: http://localhost:3050/

    postgres:
        container_name: postgres
        image: "postgres:12-alpine"
        volumes:
            - "db-data:/var/lib/postgresql/data:consistent"
            - "postgres:/data/postgres"
        ports:
            - "5432:5432"
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_DB=dbpayment
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password

    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@admin.fr"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - "${PGADMIN_PORT:-5050}:80"
        restart: unless-stopped

volumes:
    postgres:
    mongo-data:
    pgadmin:
    db-data:
