version: "3.1"

services:
    mongo:
        image: mongo
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - ./SampleCollections:/usr/local/sampleCollections
        working_dir: /usr/local/sampleCollections

    mongo-express:
        image: mongo-express
        depends_on:
            - mongo
        ports:
            - 127.0.0.1:8088:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: password

    server-only:
        image: node:alpine
        volumes:
            - "./server:/home/node/app:rw,consistent"
        working_dir: "/home/node/app"
        environment:
            JWT_SECRET: "MyBestSecret"
            MAILER_USER: "payplus.info2020@gmail.com"
            MAILER_PASS: "paypluas2020"
        command: "npm run dev"
        ports:
            - 127.0.0.1:3050:3050

    server:
        image: node:alpine
        volumes:
            - "./server:/home/node/app:rw,consistent"
        working_dir: "/home/node/app"
        environment:
            MONGODB_USER: "root"
            MONGODB_PASS: "password"
            MONGODB_DBNAME: "SampleCollections"
            DATABASE_URL: "postgres://user:password@postgres:5432/dbpayment"
            JWT_SECRET: "MyBestSecret"
            MAILER_USER: "payplus.info2020@gmail.com"
            MAILER_PASS: "paypluas2020"
            BASE_URL: "http://localhost:3050"
        depends_on:
            - postgres
            - pgadmin
            - mongo
        command: "npm run dev"
        ports:
            - 127.0.0.1:3050:3050

    client:
        build: "./docker"
        volumes:
            - "./client:/home/node/app"
        working_dir: "/home/node/app"
        command: "yarn start"
        tty: true
        stdin_open: true
        ports:
            - 127.0.0.1:3000:3000
        environment:
            REACT_APP_BACK_OFFICE_URL: http://localhost:3050/

    postgres:
        container_name: postgres
        image: "postgres:12-alpine"
        volumes:
            - "db-data:/var/lib/postgresql/data:consistent"
            - "postgres:/data/postgres"
        ports:
            - "5432:5432"
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_DB=dbpayment
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password

    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@admin.fr"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - "${PGADMIN_PORT:-5050}:80"
        restart: unless-stopped

volumes:
    postgres:
    pgadmin:
    db-data:
