###
GET http://localhost:5000


###
GET http://localhost:5000/hello

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"aaaa@test.com",
    "password": "pass"
}

###
// login admin
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"admin@admin.com",
    "password": "adminPass"
}


###
POST http://localhost:5000/register
Content-Type: application/json

{
    "email":"aaaa@test.com",
    "password": "pass",
    "firstname": "test",
    "lastname": "lastname",
    "gender":"male",
    "birthday":"2002-05-08"
}


###
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkFETUlOIiwiaWF0IjoxNTkxMDQzNjIyLCJleHAiOjE1OTEwNDcyMjJ9.rnodF4_YgdCV2A7LAmYKYn3j6HrsAhXaYzvRbJRO0A8

###
GET http://localhost:5000/users